name: Python application CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Flask app
        run: |
          nohup python -m RivertyAPI.web_api &
          sleep 5  # Wait for the Flask server to start
      - name: Run tests
        run: |
          python -m unittest discover -s UnitTests
